### ISSUE TITLE
WinError 123 while downloading

### ISSUE THREAD

**Issue by ZinRicky** [easlice/bandcamp-downloader#2]
Downloading my collection, I encountered this error

```
Traceback (most recent call last):
  File "D:\Programmi\BandcampCollectionDownloader\bandcamp-downloader.py", line 235, in <module>
    sys.exit(main())
  File "D:\Programmi\BandcampCollectionDownloader\bandcamp-downloader.py", line 111, in main
    download_album(link)
  File "D:\Programmi\BandcampCollectionDownloader\bandcamp-downloader.py", line 184, in download_album
    download_file(download_url, artist)
  File "D:\Programmi\BandcampCollectionDownloader\bandcamp-downloader.py", line 212, in download_file
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
  File "C:\Users\ricca\AppData\Local\Programs\Python\Python39\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "C:\Users\ricca\AppData\Local\Programs\Python\Python39\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: 'D:\\Programmi\\BandcampCollectionDownloader\\
```

I don’t know what causes it, but it should be noted that my collection is full of vaporwave albums (so there’s a lot of Unicode in there)

**Comment by easlice** [comment]
Ah, I might have figured it out. Looks like windows can throw a fit about ':'s and such.

I'll see about doing something to make sure paths contain only windows/linux valid characters.

**Comment by ZinRicky** [comment]
> Ok, this should be fixed with the new change I just pushed up. Maybe give it a go again and let me know if it works for you now?

The first album that was downloaded appears to have a `:` swapped with a `-`, so I think the patch is working as intended. Thanks a lot!

**Comment by easlice** [comment]
No problem, glad to get it fixed!
