### ISSUE TITLE
--extract flag attempts to extract single files that are not a .zip compressed archive 

### ISSUE THREAD

**Issue by vin-cf** [easlice/bandcamp-downloader#37]
When downloading a single file that is represented typically as an `.mp3`, `--extract` when passed as a command line argument attempts to unzip the audio file

# Reproduction steps:
`bandcamp-downloader.py {USER} -download-since "$(date +%F)"--extract`

# Result

```
Starting album downloads...
100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:59<00:00, 29.76s/album]
['/volume1/Music/smallville records/smallville records - Lea Lisa - Poem For The Lost Souls (Original Mix).mp3', '/volume1/Music/Ki Oni/Ki Oni - Indoor Plant Life I.zip']
Extracting compressed archive: /volume1/Music/smallville records/smallville records - Lea Lisa - Poem For The Lost Souls (Original Mix).mp3
Traceback (most recent call last):
  File "/volume1/homes/foo/Documents/Git/bandcamp-downloader/.venv/bin/bandcamp-downloader.py", line 458, in <module>
    sys.exit(main())
  File "/volume1/homes/foo/Documents/Git/bandcamp-downloader/.venv/bin/bandcamp-downloader.py", line 214, in main
    album_name = re.search(r'\- (.+?)\.zip$', zip).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

# Expected result
- `/volume1/Music/smallville records/smallville records - Lea Lisa - Poem For The Lost Souls (Original Mix).mp3` is not added to the list of files to unzip (extract)

**Comment by easlice** [comment]
This should be fixed now. Closing.
