### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ajcowell** [easlice/bandcamp-downloader#6]
Get this when trying to run.   

File "/Users/ajcowell/Downloads/bandcamp-downloader-master/./bandcamp-downloader.py", line 318, in <module>
    sys.exit(main())
  File "/Users/ajcowell/Downloads/bandcamp-downloader-master/./bandcamp-downloader.py", line 134, in main
    links = get_download_links_for_user(args.username)
  File "/Users/ajcowell/Downloads/bandcamp-downloader-master/./bandcamp-downloader.py", line 186, in get_download_links_for_user
    'collection_count' : data['collection_count'],

**Comment by ajcowell** [comment]
User error.

**Comment by RunningDroid** [comment]
I appear to be getting the same error, what did you do to fix this?

```
Traceback (most recent call last):
  File "/home/runningdroid/git/bandcamp-downloader/venv/bin/bandcamp-downloader.py", line 336, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runningdroid/git/bandcamp-downloader/venv/bin/bandcamp-downloader.py", line 149, in main
    links = get_download_links_for_user(args.username)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runningdroid/git/bandcamp-downloader/venv/bin/bandcamp-downloader.py", line 201, in get_download_links_for_user
    'collection_count' : data['collection_count'],
                         ~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'collection_count'
```

**Comment by easlice** [comment]
@RunningDroid There are a few things that can cause this, usually when something causes the downloader to look at the wrong url for a users profile. Can you check that you're passing your bandcamp username correctly to the script?

**Comment by RunningDroid** [comment]
I think I'm passing my username correctly, my bandcamp profile is `https://bandcamp.com/ahavo` and I'm running the downloader like this: `bandcamp-downloader.py -d ~/Archive/Bandcamp -f flac avaho`

**Comment by easlice** [comment]
Just to make absolutely sure it isn't something this easy, the url you posted says your username is `ahavo` but the command you posted has the username `avaho`. Is that just a typo in your comment but not when you're actually running the command?

**Comment by RunningDroid** [comment]
It was that easy, I'd typo'd my username in the command without noticing.
It works now, Thanks!
